FROM alpine:latest

RUN mkdir -p /usr/src/app/
WORKDIR /usr/src/app/

RUN apk add --update --no-cache python3 && ln -sf python3 /usr/bin/python
RUN python3 -m ensurepip
RUN pip3 install --no-cache --upgrade pip setuptools flask

CMD ["python", "site.py"]